# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='haegyun', max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
    ]
