# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='까페 이름')),
                ('address', models.CharField(max_length=10, verbose_name='간략한 주소')),
                ('mood', models.CharField(max_length=10, verbose_name='분위기')),
                ('week_hours', models.CharField(max_length=20, verbose_name='평일 영업시간')),
                ('satur_hours', models.CharField(max_length=20, verbose_name='토요일 영업시간')),
                ('sun_hours', models.CharField(max_length=20, verbose_name='휴일 영업시간')),
                ('has_solo_table', models.BooleanField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CafePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='광역시도')),
                ('ward', models.CharField(max_length=10, verbose_name='자치구')),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
    ]
