# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카페 이름')),
                ('address', models.CharField(max_length=20, verbose_name='간략한 주소')),
                ('mood', models.CharField(max_length=10, verbose_name='분위기')),
                ('intro', models.TextField(verbose_name='추천이유')),
                ('has_solo_table', models.BooleanField(default=False, verbose_name='1인 테이블')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='CafePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.get_upload_path)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50, verbose_name='위도')),
                ('longitude', models.CharField(max_length=50, verbose_name='경도')),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='main.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='광역시도')),
            ],
        ),
    ]
