# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42, verbose_name='까페 좌표'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_solo_table',
            field=models.BooleanField(verbose_name='1인 테이블 유무'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='intro',
            field=models.TextField(verbose_name='50자 이내 소개'),
        ),
    ]
