# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cafe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='has_solo_table',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='mood',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(max_length=20, verbose_name='위치'),
        ),
    ]
