# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160723_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50, verbose_name='위도')),
                ('longitude', models.CharField(max_length=50, verbose_name='경도')),
            ],
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='position',
        ),
        migrations.AddField(
            model_name='cafeposition',
            name='cafe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Cafe'),
        ),
    ]
