# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161028_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(max_length=50, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=50, verbose_name='카페 이름'),
        ),
    ]
