# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160826_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeposition',
            name='cafe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='main.Cafe'),
        ),
    ]
