# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_region_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 9, 0, 12, 253355, tzinfo=utc), verbose_name='등록일'),
            preserve_default=False,
        ),
    ]
