# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cafe_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='created',
            field=models.DateTimeField(auto_created=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='has_solo_table',
            field=models.BooleanField(default=False, verbose_name='1인 테이블'),
        ),
    ]
