# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161030_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='intro',
            field=models.TextField(verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
    ]
