# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160918_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
