# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160918_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='satur_hours',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='sun_hours',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='week_hours',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='region',
            field=models.ForeignKey(help_text='지역', on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
    ]
