# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161001_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='region',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='intro',
            field=models.TextField(verbose_name='추천이유'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=20, verbose_name='카페 이름'),
        ),
    ]
