# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161008_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.CharField(max_length=20, verbose_name='간략한 주소'),
        ),
    ]
